"""Вхідні дані варіантів 1-15 для лабораторної роботи №1.

У методичці 15 варіантів, а номер студента у списку групи може бути
більшим, тому його зводять до діапазону 1-15: 22 -> 22 - 15 = 7.
"""

from shared.student import VARIANT_NUMBER

VARIANTS_COUNT = 15


def to_lab_variant(variant_number: int) -> int:
    """Звести номер у списку групи до варіанту 1-15 цієї роботи."""
    if variant_number < 1:
        raise ValueError("Номер варіанту має бути додатним")
    return (variant_number - 1) % VARIANTS_COUNT + 1


LAB_VARIANT = to_lab_variant(VARIANT_NUMBER)

_ALL_REQUIRED = {
    "require_digits": True,
    "require_upper": True,
    "require_special": True,
}

# Завдання 1: паролі, критерії та заборонені паролі.
TASK1_VARIANTS = {
    1: {
        "passwords": [
            "password123",
            "Qwerty!2023",
            "admin",
            "MyP@ssw0rd",
            "123456",
            "SecurePass!",
            "test",
            "P@ssw0rd123",
            "welcome",
            "StrongP@ss1",
        ],
        "criteria": {"min_length": 8, **_ALL_REQUIRED},
        "forbidden_passwords": {
            "password",
            "123456",
            "admin",
            "test",
            "welcome",
            "qwerty",
        },
    },
    2: {
        "passwords": [
            "Hello123!",
            "simple",
            "CompL3x@Pass",
            "password",
            "Str0ng#2023",
            "weak",
            "MySecur3!",
            "12345",
            "Advanced@1",
            "basic",
        ],
        "criteria": {"min_length": 10, **_ALL_REQUIRED},
        "forbidden_passwords": {
            "password",
            "simple",
            "weak",
            "basic",
            "12345",
            "hello",
        },
    },
    3: {
        "passwords": [
            "UserPass1!",
            "temp",
            "Cyber$ecur1ty",
            "guest",
            "P0w3rful@Pass",
            "login",
            "Defens3#2023",
            "abc123",
            "Elit3@Secur",
            "demo",
        ],
        "criteria": {"min_length": 9, **_ALL_REQUIRED},
        "forbidden_passwords": {
            "temp",
            "guest",
            "login",
            "demo",
            "abc123",
            "user",
        },
    },
    4: {
        "passwords": [
            "Security@2023",
            "pass",
            "MyStr0ng#Key",
            "root",
            "Advanc3d@Pass",
            "user",
            "Protec7!Pass",
            "1234",
            "Elite@Secur1ty",
            "admin123",
        ],
        "criteria": {"min_length": 7, **_ALL_REQUIRED},
        "forbidden_passwords": {
            "pass",
            "root",
            "user",
            "1234",
            "admin123",
            "password",
        },
    },
    5: {
        "passwords": [
            "DataS3cur3!",
            "123",
            "Crypt0@Analysis",
            "test123",
            "Quantum#2023",
            "access",
            "Secur1ty@Pro",
            "password1",
            "Adv@nced123",
            "guest123",
        ],
        "criteria": {"min_length": 12, **_ALL_REQUIRED},
        "forbidden_passwords": {
            "123",
            "test123",
            "access",
            "password1",
            "guest123",
            "admin",
        },
    },
    6: {
        "passwords": [
            "InfoS3c@2023",
            "simple123",
            "Def3ns3@Key",
            "public",
            "Encrypt3d#Pass",
            "basic123",
            "Secur3@Analysis",
            "temp123",
            "Pr0t3ct@Data",
            "default",
        ],
        "criteria": {"min_length": 8, **_ALL_REQUIRED},
        "forbidden_passwords": {
            "simple123",
            "public",
            "basic123",
            "temp123",
            "default",
            "guest",
        },
    },
    7: {
        "passwords": [
            "NetworkS3c!",
            "easy",
            "Firewa11@Pass",
            "anonymous",
            "Intrus10n#Detect",
            "sample",
            "Malwar3@Scan",
            "qwerty",
            "Vulnerab1l!ty",
            "common",
        ],
        "criteria": {"min_length": 9, **_ALL_REQUIRED},
        "forbidden_passwords": {
            "easy",
            "anonymous",
            "sample",
            "qwerty",
            "common",
            "password",
        },
    },
    8: {
        "passwords": [
            "ThreatH@nt3r",
            "weak123",
            "P3n3trat10n@Test",
            "visitor",
            "Cyber@Defense2023",
            "normal",
            "Incident@R3sp0nse",
            "standard",
            "Risk@Analys1s",
            "typical",
        ],
        "criteria": {"min_length": 10, **_ALL_REQUIRED},
        "forbidden_passwords": {
            "weak123",
            "visitor",
            "normal",
            "standard",
            "typical",
            "admin",
        },
    },
    9: {
        "passwords": [
            "Digital@F0r3nsics",
            "plain",
            "Encrypt10n@Key",
            "member",
            "Security@Audit2023",
            "regular",
            "Hack3r@D3fense",
            "ordinary",
            "Threat@Intel",
            "usual",
        ],
        "criteria": {"min_length": 8, **_ALL_REQUIRED},
        "forbidden_passwords": {
            "plain",
            "member",
            "regular",
            "ordinary",
            "usual",
            "user",
        },
    },
    10: {
        "passwords": [
            "S0cial@Engineer",
            "basic",
            "Phish1ng@D3tect",
            "client",
            "Ransomwar3@Protect",
            "general",
            "Zero@D4y",
            "generic",
            "Bug@B0unty",
            "standard123",
        ],
        "criteria": {"min_length": 11, **_ALL_REQUIRED},
        "forbidden_passwords": {
            "basic",
            "client",
            "general",
            "generic",
            "standard123",
            "guest",
        },
    },
    11: {
        "passwords": [
            "APT@Detect10n",
            "simple",
            "Red@Team2023",
            "participant",
            "Blue@T3am",
            "common123",
            "Purple@T34m",
            "regular123",
            "Gr33n@Team",
            "normal123",
        ],
        "criteria": {"min_length": 7, **_ALL_REQUIRED},
        "forbidden_passwords": {
            "simple",
            "participant",
            "common123",
            "regular123",
            "normal123",
            "test",
        },
    },
    12: {
        "passwords": [
            "SIEM@An4lysis",
            "easy123",
            "S0C@Analyst",
            "observer",
            "Threat@Hunt1ng",
            "viewer",
            "Incid3nt@Handle",
            "monitor",
            "Log@An4lysis",
            "watcher",
        ],
        "criteria": {"min_length": 9, **_ALL_REQUIRED},
        "forbidden_passwords": {
            "easy123",
            "observer",
            "viewer",
            "monitor",
            "watcher",
            "admin",
        },
    },
    13: {
        "passwords": [
            "Compli4nc3@Check",
            "weak",
            "Risk@Ass3ssment",
            "guest",
            "Vulner4bility@Scan",
            "temp",
            "P3netration@Test",
            "demo",
            "S3curity@Audit",
            "trial",
        ],
        "criteria": {"min_length": 8, **_ALL_REQUIRED},
        "forbidden_passwords": {
            "weak",
            "guest",
            "temp",
            "demo",
            "trial",
            "password",
        },
    },
    14: {
        "passwords": [
            "C2@Command",
            "plain123",
            "Backdoor@D3tect",
            "public123",
            "Rootk1t@Hunt",
            "access123",
            "Exploit@An4lysis",
            "basic",
            "Payload@D3code",
            "default123",
        ],
        "criteria": {"min_length": 10, **_ALL_REQUIRED},
        "forbidden_passwords": {
            "plain123",
            "public123",
            "access123",
            "basic",
            "default123",
            "user",
        },
    },
    15: {
        "passwords": [
            "IoT@S3curity",
            "standard",
            "Blockchain@Pr0tect",
            "typical123",
            "AI@Cybersec",
            "normal",
            "Quantum@Crypt0",
            "general123",
            "Edge@S3curity",
            "common",
        ],
        "criteria": {"min_length": 8, **_ALL_REQUIRED},
        "forbidden_passwords": {
            "standard",
            "typical123",
            "normal",
            "general123",
            "common",
            "guest",
        },
    },
}


def _user(role: str, clearance: int, department: str, active: bool) -> dict:
    """Створити запис користувача у форматі методички."""
    return {
        "role": role,
        "clearance": clearance,
        "department": department,
        "active": active,
    }


# Завдання 2: користувачі, ресурси, рівні безпеки та блокування.
TASK2_VARIANTS = {
    1: {
        "users": {
            "admin001": _user("administrator", 4, "IT", True),
            "user123": _user("analyst", 2, "Security", True),
            "guest789": _user("guest", 1, "External", True),
            "manager456": _user("manager", 3, "Operations", True),
            "contractor99": _user("contractor", 1, "External", False),
        },
        "resources": [
            ("database_backup", 4),
            ("user_logs", 2),
            ("public_docs", 1),
            ("financial_reports", 3),
            ("system_config", 4),
            ("training_materials", 1),
            ("security_policies", 3),
            ("audit_logs", 4),
            ("employee_data", 3),
            ("temp_files", 1),
        ],
        "security_levels": ("Public", "Internal", "Confidential", "Secret"),
        "blocked_users": {"contractor99", "temp_user", "suspended_acc"},
    },
    2: {
        "users": {
            "sysadmin02": _user("system_admin", 4, "Infrastructure", True),
            "analyst234": _user("security_analyst", 3, "SOC", True),
            "developer567": _user("developer", 2, "Development", True),
            "intern890": _user("intern", 1, "HR", True),
            "external123": _user("external", 1, "Vendor", False),
        },
        "resources": [
            ("prod_database", 4),
            ("dev_environment", 2),
            ("documentation", 1),
            ("source_code", 3),
            ("server_configs", 4),
            ("test_data", 2),
            ("compliance_docs", 3),
            ("system_logs", 4),
            ("project_files", 2),
            ("public_wiki", 1),
        ],
        "security_levels": ("Open", "Internal", "Restricted", "Top Secret"),
        "blocked_users": {"external123", "old_account", "test_user"},
    },
    3: {
        "users": {
            "security_chief": _user("security_officer", 4, "Security", True),
            "network_admin": _user("network_admin", 3, "Network", True),
            "help_desk": _user("support", 1, "Support", True),
            "auditor_ext": _user("auditor", 3, "Audit", True),
            "temp_worker": _user("temporary", 1, "Temp", False),
        },
        "resources": [
            ("incident_reports", 4),
            ("network_topology", 3),
            ("user_manual", 1),
            ("vulnerability_scans", 3),
            ("root_access", 4),
            ("help_tickets", 1),
            ("penetration_tests", 4),
            ("firewall_rules", 3),
            ("software_licenses", 2),
            ("faq_docs", 1),
        ],
        "security_levels": (
            "Unrestricted",
            "Limited",
            "Sensitive",
            "Classified",
        ),
        "blocked_users": {"temp_worker", "fired_employee", "compromised_acc"},
    },
    4: {
        "users": {
            "ciso_office": _user("ciso", 4, "Executive", True),
            "threat_hunter": _user("threat_analyst", 3, "Threat Intel", True),
            "junior_dev": _user("junior_developer", 2, "Development", True),
            "visitor_acc": _user("visitor", 1, "Guest", True),
            "legacy_sys": _user("legacy", 2, "Legacy", False),
        },
        "resources": [
            ("threat_intelligence", 4),
            ("malware_samples", 3),
            ("coding_guidelines", 2),
            ("visitor_wifi", 1),
            ("strategic_plans", 4),
            ("demo_environment", 1),
            ("risk_assessments", 3),
            ("crypto_keys", 4),
            ("api_documentation", 2),
            ("guest_portal", 1),
        ],
        "security_levels": ("Guest", "Employee", "Privileged", "Executive"),
        "blocked_users": {"legacy_sys", "malicious_user", "expired_guest"},
    },
    5: {
        "users": {
            "forensic_lead": _user("forensic_analyst", 4, "Forensics", True),
            "compliance_off": _user(
                "compliance_officer", 3, "Compliance", True
            ),
            "trainee_sec": _user("trainee", 1, "Training", True),
            "vendor_tech": _user("vendor_support", 2, "Vendor", True),
            "archived_usr": _user("archived", 1, "Archive", False),
        },
        "resources": [
            ("forensic_images", 4),
            ("compliance_reports", 3),
            ("training_videos", 1),
            ("vendor_tools", 2),
            ("evidence_locker", 4),
            ("certification_docs", 1),
            ("audit_findings", 3),
            ("chain_of_custody", 4),
            ("support_tickets", 2),
            ("learning_modules", 1),
        ],
        "security_levels": ("Basic", "Standard", "Protected", "Maximum"),
        "blocked_users": {
            "archived_usr",
            "terminated_vendor",
            "security_breach",
        },
    },
    6: {
        "users": {
            "red_team_lead": _user("red_team", 4, "Red Team", True),
            "blue_team_analyst": _user("blue_team", 3, "Blue Team", True),
            "purple_team_coord": _user("purple_team", 3, "Purple Team", True),
            "student_intern": _user("student", 1, "Academia", True),
            "retired_expert": _user("retired", 2, "Emeritus", False),
        },
        "resources": [
            ("attack_scenarios", 4),
            ("defense_playbooks", 3),
            ("exercise_plans", 3),
            ("research_papers", 1),
            ("exploit_tools", 4),
            ("student_resources", 1),
            ("simulation_results", 3),
            ("red_team_tools", 4),
            ("blue_team_reports", 3),
            ("public_research", 1),
        ],
        "security_levels": (
            "Academic",
            "Operational",
            "Tactical",
            "Strategic",
        ),
        "blocked_users": {
            "retired_expert",
            "academic_violator",
            "leaked_account",
        },
    },
    7: {
        "users": {
            "incident_commander": _user("incident_response", 4, "CSIRT", True),
            "malware_analyst": _user(
                "malware_researcher", 3, "Research", True
            ),
            "monitoring_tech": _user("monitoring", 2, "NOC", True),
            "customer_rep": _user("customer_service", 1, "Customer", True),
            "backup_service": _user("service_account", 2, "System", False),
        },
        "resources": [
            ("incident_playbook", 4),
            ("malware_lab", 3),
            ("monitoring_dashboards", 2),
            ("customer_portal", 1),
            ("emergency_procedures", 4),
            ("service_desk", 1),
            ("reverse_engineering", 3),
            ("alert_systems", 2),
            ("escalation_matrix", 3),
            ("knowledge_base", 1),
        ],
        "security_levels": (
            "Public Access",
            "Authorized",
            "Privileged",
            "Critical",
        ),
        "blocked_users": {
            "backup_service",
            "deactivated_svc",
            "policy_violation",
        },
    },
    8: {
        "users": {
            "crypto_specialist": _user(
                "cryptographer", 4, "Cryptography", True
            ),
            "privacy_officer": _user("privacy_analyst", 3, "Privacy", True),
            "data_scientist": _user("data_analyst", 2, "Analytics", True),
            "field_engineer": _user("field_support", 2, "Field Ops", True),
            "test_account": _user("testing", 1, "QA", False),
        },
        "resources": [
            ("encryption_keys", 4),
            ("privacy_policies", 3),
            ("anonymized_data", 2),
            ("field_reports", 2),
            ("crypto_algorithms", 4),
            ("consent_forms", 1),
            ("data_classification", 3),
            ("key_management", 4),
            ("statistical_models", 2),
            ("public_datasets", 1),
        ],
        "security_levels": (
            "Unclassified",
            "For Official Use",
            "Confidential",
            "Secret",
        ),
        "blocked_users": {
            "test_account",
            "gdpr_violation",
            "data_breach_user",
        },
    },
    9: {
        "users": {
            "cloud_architect": _user("cloud_security", 4, "Cloud", True),
            "devops_engineer": _user("devops", 3, "DevOps", True),
            "qa_tester": _user("quality_assurance", 2, "QA", True),
            "partner_access": _user("partner", 2, "Partnership", True),
            "migrated_user": _user("migrated", 1, "Migration", False),
        },
        "resources": [
            ("cloud_configs", 4),
            ("deployment_pipelines", 3),
            ("test_environments", 2),
            ("partner_apis", 2),
            ("infrastructure_code", 4),
            ("shared_resources", 1),
            ("container_registry", 3),
            ("secrets_vault", 4),
            ("build_artifacts", 2),
            ("public_endpoints", 1),
        ],
        "security_levels": (
            "Development",
            "Staging",
            "Production",
            "Critical Infrastructure",
        ),
        "blocked_users": {
            "migrated_user",
            "container_breach",
            "pipeline_compromise",
        },
    },
    10: {
        "users": {
            "iot_specialist": _user("iot_security", 3, "IoT", True),
            "mobile_analyst": _user("mobile_security", 3, "Mobile", True),
            "web_developer": _user("web_developer", 2, "Web", True),
            "api_consumer": _user("api_user", 2, "Integration", True),
            "demo_account": _user("demonstration", 1, "Demo", False),
        },
        "resources": [
            ("iot_firmware", 3),
            ("mobile_policies", 3),
            ("web_applications", 2),
            ("api_gateway", 2),
            ("device_certificates", 3),
            ("app_store", 1),
            ("vulnerability_database", 3),
            ("device_management", 3),
            ("integration_docs", 2),
            ("demo_content", 1),
        ],
        "security_levels": (
            "Consumer",
            "Business",
            "Enterprise",
            "Critical Systems",
        ),
        "blocked_users": {
            "demo_account",
            "compromised_device",
            "malicious_app",
        },
    },
    11: {
        "users": {
            "risk_manager": _user("risk_analyst", 4, "Risk Management", True),
            "business_analyst": _user("business_analyst", 2, "Business", True),
            "legal_counsel": _user("legal", 3, "Legal", True),
            "contractor_dev": _user("contractor", 2, "Contract", True),
            "obsolete_system": _user("legacy_system", 1, "Legacy", False),
        },
        "resources": [
            ("risk_registers", 4),
            ("business_requirements", 2),
            ("legal_documents", 3),
            ("contract_code", 2),
            ("governance_framework", 4),
            ("meeting_minutes", 1),
            ("regulatory_reports", 3),
            ("executive_dashboards", 4),
            ("project_specs", 2),
            ("public_statements", 1),
        ],
        "security_levels": (
            "Public",
            "Internal Use",
            "Restricted",
            "Highly Restricted",
        ),
        "blocked_users": {"obsolete_system", "contract_expired", "legal_hold"},
    },
    12: {
        "users": {
            "devsecops_lead": _user("devsecops", 4, "DevSecOps", True),
            "security_engineer": _user(
                "security_engineer", 3, "Security Engineering", True
            ),
            "automation_tech": _user("automation", 2, "Automation", True),
            "api_developer": _user("api_developer", 2, "API", True),
            "sandbox_env": _user("sandbox", 1, "Testing", False),
        },
        "resources": [
            ("security_pipelines", 4),
            ("secure_coding_standards", 3),
            ("automation_scripts", 2),
            ("api_specifications", 2),
            ("threat_models", 4),
            ("testing_frameworks", 1),
            ("security_gates", 3),
            ("vulnerability_scans", 4),
            ("integration_tests", 2),
            ("mock_services", 1),
        ],
        "security_levels": (
            "Sandbox",
            "Development",
            "Secure",
            "Production Critical",
        ),
        "blocked_users": {"sandbox_env", "pipeline_breach", "automation_fail"},
    },
    13: {
        "users": {
            "ai_security_expert": _user("ai_security", 4, "AI Security", True),
            "ml_engineer": _user("ml_engineer", 3, "Machine Learning", True),
            "data_engineer": _user(
                "data_engineer", 2, "Data Engineering", True
            ),
            "research_assistant": _user("researcher", 2, "Research", True),
            "training_bot": _user("bot_account", 1, "Automation", False),
        },
        "resources": [
            ("ai_models", 4),
            ("training_datasets", 3),
            ("data_pipelines", 2),
            ("research_notebooks", 2),
            ("model_artifacts", 4),
            ("synthetic_data", 1),
            ("adversarial_tests", 3),
            ("model_registry", 4),
            ("feature_stores", 2),
            ("public_models", 1),
        ],
        "security_levels": (
            "Open Source",
            "Internal Research",
            "Proprietary",
            "Trade Secret",
        ),
        "blocked_users": {"training_bot", "model_theft", "data_poisoning_acc"},
    },
    14: {
        "users": {
            "blockchain_dev": _user(
                "blockchain_developer", 3, "Blockchain", True
            ),
            "smart_contract_auditor": _user(
                "contract_auditor", 3, "Audit", True
            ),
            "crypto_trader": _user("trader", 2, "Trading", True),
            "wallet_user": _user("wallet_user", 1, "Users", True),
            "mining_pool": _user("miner", 1, "Mining", False),
        },
        "resources": [
            ("smart_contracts", 3),
            ("audit_reports", 3),
            ("trading_algorithms", 2),
            ("wallet_interface", 1),
            ("private_keys", 3),
            ("public_blockchain", 1),
            ("defi_protocols", 3),
            ("validator_nodes", 3),
            ("market_data", 2),
            ("community_forum", 1),
        ],
        "security_levels": (
            "Public Blockchain",
            "Permissioned",
            "Private Network",
            "Institutional",
        ),
        "blocked_users": {"mining_pool", "flash_loan_attack", "rug_pull_scam"},
    },
    15: {
        "users": {
            "quantum_researcher": _user(
                "quantum_security", 4, "Quantum Research", True
            ),
            "post_quantum_dev": _user(
                "pq_cryptographer", 4, "Post-Quantum", True
            ),
            "network_security": _user(
                "network_security", 3, "Network Security", True
            ),
            "crypto_intern": _user("crypto_intern", 1, "Internship", True),
            "quantum_sim": _user("simulator", 2, "Simulation", False),
        },
        "resources": [
            ("quantum_algorithms", 4),
            ("pq_implementations", 4),
            ("network_protocols", 3),
            ("learning_materials", 1),
            ("quantum_keys", 4),
            ("educational_content", 1),
            ("hybrid_systems", 3),
            ("quantum_computers", 4),
            ("crypto_libraries", 2),
            ("tutorials", 1),
        ],
        "security_levels": (
            "Educational",
            "Research",
            "Classified Research",
            "Quantum Secure",
        ),
        "blocked_users": {"quantum_sim", "quantum_attack", "algorithm_theft"},
    },
}

# Завдання 3: (алгоритм хешування, мінімальна довжина пароля).
TASK3_VARIANTS = {
    1: ("sha3_512", 12),
    2: ("sha3_224", 10),
    3: ("sha1", 8),
    4: ("sha512", 14),
    5: ("sha3_256", 16),
    6: ("blake2s", 9),
    7: ("sha384", 15),
    8: ("sha256", 11),
    9: ("sha224", 13),
    10: ("sha3_384", 10),
    11: ("blake2b", 12),
    12: ("md5", 8),
    13: ("sha3_256", 14),
    14: ("sha512", 16),
    15: ("sha1", 9),
}
